<a href="https://colab.research.google.com/github/sugimotoh/seminar2018/blob/master/Decile_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!ls

drive  sample_data

In [4]:
import pandas as pd
df_goods = pd.read_excel("/content/drive/MyDrive/data_open/商品.xls")
df_sales = pd.read_excel("/content/drive/MyDrive/data_open/売上.xls")
df_custm = pd.read_excel("/content/drive/MyDrive/data_open/顧客.xls")

In [13]:
df_goods
df_sales
df_custm

    顧客ID     名前        なまえ      郵便番号                住所          固定電話
0      1  田中　正子    たなか　まさこ  817-0021      城南区七隈１０丁目1-9  092-321-1111
1      2   関口　誠   せきぐち　まこと  814-1011      城南区松町3-1-109  094-543-1223
2      3   衛藤　文     えとう　あや  815-0031     早良区矢部2-10-109  092-567-8912
3      4   斎藤雅代   さいとう　まさよ  821-2112           南区新町３－８  092-342-1199
4      5  田中　幸子    たなか　さちこ  872-0001           西区岬台３－４  092-123-9898
5      6  近藤　和子   こんどう　かずこ  871-0002          早良区豊中１－９  092-234-8765
6      7  佐藤　涼子   さとう　りょうこ  818-0200          南区北川４－１０  092-767-1232
7      8  石橋　孝子   いしばし　たかこ  874-9101        早良区原田４－９－４  092-343-5566
8      9   金子　聖    かねこ　ひじり  821-2211         西区金田1-9-4  092-888-4563
9     10  大野　瑞希    おおの　みずき  830-0111          前原市広島２－７  094-173-3490
10    11  小林　念待   こばやし　ねんじ  123-6578           北区大橋4-1  018-183-1823
11    12   清水　計     しみず　けい  234-5912         中央区1-9-10  189-183-8291
12    13  宮沢　利香    みやざわ　りか  432-8721           東区71-90  297-289-2829
13    14  内田　里奈     うちだ　りな  876-2230          豊島区7-2-1  593-289-2893
14    15  米倉　良子  よねくら　りょうこ  230-7629          世田谷区3-91  922-283-8392
15    16  麻野　敦子    あさの　あつこ  342-9201         中央区3-2-10  292-592-2982
16    17  神田　正紀    かんだ　まさき  120-0998       北区南銀座3-10-9  628-283-2872
17    18  松田　清子    まつだ　せいこ  410-4598       住吉区若松2-77-1  382-283-2839
18    19   福留　功   ふくとめ　いさお  718-9280  小倉北区国分2-10-7-809  593-283-1934
19    20   井原　武    いはら　たけし  510-0091      門司区門司6-6-209  827-280-2839
20    21  西田　俊幸   にしだ　としゆき  120-3401        筑紫郡田中3-2-1  203-965-2839
21    22  武田　哲也    たけだ　てつや  459-0183   八女市黒木8-10-9-109  503-382-8492
22    23  伊藤　志朗    いとう　しろう  714-9049   鹿児島市下田80-10-302  038-282-1829
23    24  岡　久美子     おか　くみこ  209-7863      大村市金岡町2-10-1  393-850-2983
24    25  竹内　裕子   たけうち　ゆうこ  409-6293       大分市矢坂3-10-1  392-183-3829
25    26   安部　弘     あべ　ひろし  600-4320         福岡町3-10-2  062-382-2739
26    27  松下　由紀    まつした　ゆき  619-4501          多久市玉名3-1  027-473-2829
27    28  久本　正美   ひさもと　まさみ  309-9090       中央区浜町4-1-10  528-383-2390
28    29  中嶋　孝治   なかじま　こうじ  999-3918         中央区川田5-10  492-283-2829
29    30  田村　政和   たむら　まさかず  502-9182     中央区広川6-10-203  492-183-2819
30    31  松形　弘樹   まつかた　ひろき  509-9010       中央区高田3-10-1  762-283-8302
31    32  筑紫　哲哉    ちくし　てつや  209-2092         南区大阪3-1-1  629-181-1829
32    33  広末　亮子  ひろすえ　りょうこ  301-9062           北区大安4-3  393-183-1829
33    34  中村　正敏  なかむら　まさとし  601-7294        北区南町3-10-2  120-283-1829
34    35  澤田　彩子    さわだ　あやこ  401-4076        北区大町3-10-4  832-181-1934
35    36   相川　章   あいかわ　しょう  871-9273          北区神田4-78  392-181-3822
36    37   中畑　潔   なかはた　きよし  209-7621          北区池田4-18  528-183-1839
37    38  堀内　常雄   ほりうち　つねお  810-6826           南区大島5-3  492-128-1930
38    39   菊川　礼    きくかわ　れい  938-9183         南区藤の木台3-1  816-392-4921
39    40  武田　淳二   たけだ　じゅんじ  982-7263           南区勝山7-1  103-133-8592
40    41  香山　雄三   かやま　ゆうぞう  817-2719           東区園田4-1  392-193-3839
41    42  矢田　彰子     やた　あきこ  612-3818       東区左町3-1-201  592-198-1939
42    43   吉沢　優    よしざわ　ゆう  402-8176          東区大町3-11  293-495-9271
43    44   泉　元也    いずみ　もとや  378-8193           南区飯坂7-4  726-289-1938
44    45  藤岡　卓也   ふじおか　たくや  193-3872           南区八尾6-2  629-019-1839
45    46   藤島　功    ふじしま　こう  193-9273      南区木島8-20-603  901-382-2837
46    47  長瀬　智哉    ながせ　ともや  204-3892      西区高木4-30-204  193-389-3823
47    48  稲垣　淳二  いながき　じゅんじ  592-2873           西区千里5-2  108-383-2849
48    49  中井　雅弘   なかい　まさひろ  402-2839       西区北島3-1-402  928-479-3849
49    50  木村　琢也    きむら　たくや  692-2839           西区大隈3-1  730-283-4972

In [12]:
df_goods_sales = pd.merge(df_goods,df_sales,on='商品ID',how='inner')
df_goods_sales

     商品ID  商品カテゴリー                 商品名   売価         日付        時間  店舗  顧客ID
0       1        1                きゅうり  100 2003-07-01  10:01:00   1     1
1       1        1                きゅうり  100 2003-07-02  10:01:00   1     4
2       1        1                きゅうり  100 2003-07-02  10:01:00   1     1
3       1        1                きゅうり  100 2003-07-02  10:01:00   1    10
4       1        1                きゅうり  100 2003-07-02  10:01:00   1     9
..    ...      ...                 ...  ...        ...       ...  ..   ...
995   100       10  ペットボトル2000六甲のおいしい水  260 2003-07-03  10:01:00   1    26
996   100       10  ペットボトル2000六甲のおいしい水  260 2003-07-03  10:01:00   1    34
997   100       10  ペットボトル2000六甲のおいしい水  260 2003-07-04  10:01:00   1     1
998   100       10  ペットボトル2000六甲のおいしい水  260 2003-07-07  10:01:00   1     1
999   100       10  ペットボトル2000六甲のおいしい水  260 2003-07-07  10:01:00   1     3

[1000 rows x 8 columns]

In [15]:
df_goods_sales_custm = pd.merge(df_goods_sales,df_custm,on='顧客ID',how='inner')
df_goods_sales_custm

     商品ID  商品カテゴリー                 商品名  ...      郵便番号             住所          固定電話
0       1        1                きゅうり  ...  817-0021   城南区七隈１０丁目1-9  092-321-1111
1       1        1                きゅうり  ...  817-0021   城南区七隈１０丁目1-9  092-321-1111
2       1        1                きゅうり  ...  817-0021   城南区七隈１０丁目1-9  092-321-1111
3       1        1                きゅうり  ...  817-0021   城南区七隈１０丁目1-9  092-321-1111
4       1        1                きゅうり  ...  817-0021   城南区七隈１０丁目1-9  092-321-1111
..    ...      ...                 ...  ...       ...            ...           ...
995    65        7                 牛肉２  ...  815-0031  早良区矢部2-10-109  092-567-8912
996    67        7                 鶏肉１  ...  815-0031  早良区矢部2-10-109  092-567-8912
997    79        8                  卵２  ...  815-0031  早良区矢部2-10-109  092-567-8912
998    90        9             惣菜詰め合わせ  ...  815-0031  早良区矢部2-10-109  092-567-8912
999   100       10  ペットボトル2000六甲のおいしい水  ...  815-0031  早良区矢部2-10-109  092-567-8912

[1000 rows x 13 columns]

In [27]:
df_filter=df_goods_sales_custm[['名前', '売価']]

In [30]:
 decil=pd.DataFrame(df_filter.groupby('名前').sum())
 decil.head()

         売価
名前
中井　雅弘  6160
中嶋　孝治  2930
中村　正敏  6730
中畑　潔   7260
久本　正美  6200

In [31]:
parties = decil.quantile(q=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]).to_dict()
parties

{'売価': {0.1: 1884.0000000000002,
  0.2: 2796.0,
  0.3: 3896.0,
  0.4: 4812.0,
  0.5: 6180.0,
  0.6: 6941.999999999999,
  0.7: 10541.0,
  0.8: 12824.0,
  0.9: 15227.0}}

In [32]:
def cal_decil(x, col, df):
    if x <= df[col][0.1]:
        return 1
    elif x <= df[col][0.2]:
        return 2
    elif x <= df[col][0.3]: 
        return 3
    elif x <= df[col][0.4]: 
        return 4
    elif x <= df[col][0.5]: 
        return 5
    elif x <= df[col][0.6]: 
        return 6
    elif x <= df[col][0.7]: 
        return 7
    elif x <= df[col][0.8]: 
        return 8
    elif x <= df[col][0.9]: 
        return 9
    else:
        return 10

In [33]:
decil['Decil_score'] = decil['売価'].apply(cal_decil, args=('売価', parties))
decil.head()

         売価  Decil_score
名前
中井　雅弘  6160            5
中嶋　孝治  2930            3
中村　正敏  6730            6
中畑　潔   7260            7
久本　正美  6200            6

In [34]:
decil = decil.sort_values('売価', ascending=False)
decil['Cumsum'] = decil['売価'].cumsum()
decil['Cumprod'] = decil['Cumsum'] / decil['Cumsum'].max()
decil

          売価  Decil_score  Cumsum   Cumprod
名前
田中　正子  34640           10   34640  0.088001
泉　元也   20700           10   55340  0.140589
藤岡　卓也  20230           10   75570  0.191982
佐藤　涼子  15960           10   91530  0.232528
大野　瑞希  15470           10  107000  0.271829
木村　琢也  15200            9  122200  0.310444
松田　清子  13890            9  136090  0.345731
武田　哲也  13590            9  149680  0.380256
広末　亮子  13360            9  163040  0.414196
金子　聖   12840            9  175880  0.446816
小林　念待  12820            8  188700  0.479384
神田　正紀  12820            8  201520  0.511953
宮沢　利香  12290            8  213810  0.543175
筑紫　哲哉  11930            8  225740  0.573483
関口　誠   10660            8  236400  0.600564
田中　幸子  10490            7  246890  0.627213
斎藤雅代    8880            7  255770  0.649773
岡　久美子   8790            7  264560  0.672103
香山　雄三   7420            7  271980  0.690953
中畑　潔    7260            7  279240  0.709397
中村　正敏   6730            6  285970  0.726494
安部　弘    6660            6  292630  0.743414
清水　計    6430            6  299060  0.759749
米倉　良子   6350            6  305410  0.775881
久本　正美   6200            6  311610  0.791632
中井　雅弘   6160            5  317770  0.807281
田村　政和   5750            5  323520  0.821889
竹内　裕子   5360            5  328880  0.835505
松形　弘樹   5110            5  333990  0.848487
井原　武    4860            5  338850  0.860834
吉沢　優    4740            4  343590  0.872876
内田　里奈   4540            4  348130  0.884409
稲垣　淳二   4330            4  352460  0.895409
伊藤　志朗   3950            4  356410  0.905444
福留　功    3920            4  360330  0.915403
菊川　礼    3840            3  364170  0.925158
衛藤　文    3630            3  367800  0.934380
藤島　功    3540            3  371340  0.943373
中嶋　孝治   2930            3  374270  0.950817
近藤　和子   2830            3  377100  0.958006
西田　俊幸   2660            2  379760  0.964764
堀内　常雄   2590            2  382350  0.971344
武田　淳二   2460            2  384810  0.977593
長瀬　智哉   2010            2  386820  0.982699
矢田　彰子   1930            2  388750  0.987603
麻野　敦子   1470            1  390220  0.991337
松下　由紀   1180            1  391400  0.994335
相川　章    1090            1  392490  0.997104
澤田　彩子    890            1  393380  0.999365
石橋　孝子    250            1  393630  1.000000

In [35]:
decil[['Decil_score', 'Cumprod']].groupby('Decil_score').max() \
    .reset_index().sort_values('Decil_score', ascending=False)

   Decil_score   Cumprod
9           10  0.271829
8            9  0.446816
7            8  0.600564
6            7  0.709397
5            6  0.791632
4            5  0.860834
3            4  0.915403
2            3  0.958006
1            2  0.987603
0            1  1.000000

# 新しいセクション